define UBUNTU_CLOUD_INIT_USER_DATA_TEMPLATE
$(CLOUD_INIT_USER_DATA_TEMPLATE)
packages:
- gcc
- make
endef

DEBIAN_CLOUD_INIT_USER_DATA_TEMPLATE = $(UBUNTU_CLOUD_INIT_USER_DATA_TEMPLATE)

define FEDORA_CLOUD_INIT_USER_DATA_TEMPLATE
$(CLOUD_INIT_USER_DATA_TEMPLATE)
packages:
- gcc
- make
endef

define OPENSUSE_tumbleweed_CLOUD_INIT_USER_DATA_TEMPLATE
$(CLOUD_INIT_USER_DATA_TEMPLATE)
packages:
- gcc
- make
endef
